// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx1qlG4wSYBov9yEmCbDy6hBrM99Kack4',
    appId: '1:739935924768:web:595f296cbcd1d3f2058245',
    messagingSenderId: '739935924768',
    projectId: 'arexperience-auth',
    authDomain: 'arexperience-auth.firebaseapp.com',
    databaseURL: 'https://arexperience-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arexperience-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClOpTEUk1V_tBxMNqPkVT4IvNHk1ujoU4',
    appId: '1:739935924768:android:7ae410db5749055c058245',
    messagingSenderId: '739935924768',
    projectId: 'arexperience-auth',
    databaseURL: 'https://arexperience-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arexperience-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwuj2KCxT5SXiXyiBwt4cfo7ipzK6u3n4',
    appId: '1:739935924768:ios:70ffb77e9f29b1c6058245',
    messagingSenderId: '739935924768',
    projectId: 'arexperience-auth',
    databaseURL: 'https://arexperience-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arexperience-auth.appspot.com',
    iosClientId: '739935924768-pleqf87c86o53f2enbdaa37oj2v3oh2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.arxperience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwuj2KCxT5SXiXyiBwt4cfo7ipzK6u3n4',
    appId: '1:739935924768:ios:630dd0712a956ba4058245',
    messagingSenderId: '739935924768',
    projectId: 'arexperience-auth',
    databaseURL: 'https://arexperience-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arexperience-auth.appspot.com',
    iosClientId: '739935924768-n8sqjgl15sdr8ihqm9cen0obgoapor13.apps.googleusercontent.com',
    iosBundleId: 'com.example.arxperience.RunnerTests',
  );
}
